import { MwEventDto } from '@mobile-worker/timesheet/shared/types';
import { getUuid } from '@ngrx/data';

import { subDays } from 'date-fns';
import { toDateString } from '@mobile-worker/timesheet/shared/helpers';

const now = new Date();

const daysFromNow = (days: number) => toDateString(subDays(now, days));

export const MW_EVENTS_MOCK: MwEventDto[] = [
  {
    id: getUuid(),
    eventTypeName: 'Planning',
    date: toDateString(now),
    quantity: 120,
    price: 0,
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 3,
    firstTaskStart: `${toDateString(now)} 07:00`,
    lastTaskEnd: `${toDateString(now)} 17:00`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Implementing',
    date: toDateString(now),
    quantity: 120,
    price: 0,
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 3,
    firstTaskStart: `${toDateString(now)} 07:00`,
    lastTaskEnd: `${toDateString(now)} 17:00`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Testing',
    date: toDateString(now),
    quantity: 95,
    price: 0,
    isExpenseType: true,
    isHoursEventType: false,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 3,
    firstTaskStart: `${toDateString(now)} 07:00`,
    lastTaskEnd: `${toDateString(now)} 17:00`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Buy hardware',
    date: daysFromNow(1),
    quantity: 500,
    price: 142,
    isExpenseType: true,
    isHoursEventType: false,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 2,
    firstTaskStart: `${daysFromNow(1)} 10:20`,
    lastTaskEnd: `${daysFromNow(1)} 18:05`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Sell hardware',
    date: daysFromNow(1),
    quantity: 17,
    price: 11111,
    isExpenseType: true,
    isHoursEventType: false,
    isAdditionalHoursEventType: false,
    isWorkHour: false,
    isApproved: false,
    isRejected: true,
    tasksCount: 2,
    firstTaskStart: `${daysFromNow(1)} 10:20`,
    lastTaskEnd: `${daysFromNow(1)} 18:05`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Planning',
    date: daysFromNow(2),
    quantity: 60,
    price: 0,
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 3,
    firstTaskStart: `${daysFromNow(2)} 09:20`,
    lastTaskEnd: `${daysFromNow(2)} 17:30`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Implementing',
    date: daysFromNow(2),
    quantity: 45,
    price: 0,
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: false,
    isRejected: false,
    tasksCount: 3,
    firstTaskStart: `${daysFromNow(2)} 09:20`,
    lastTaskEnd: `${daysFromNow(2)} 17:30`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Testing',
    date: daysFromNow(2),
    quantity: 3,
    price: 0,
    isExpenseType: false,
    isHoursEventType: false,
    isAdditionalHoursEventType: true,
    isWorkHour: true,
    isApproved: false,
    isRejected: false,
    tasksCount: 3,
    firstTaskStart: `${daysFromNow(2)} 09:20`,
    lastTaskEnd: `${daysFromNow(2)} 17:30`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Daily stand up',
    date: daysFromNow(3),
    quantity: 65,
    price: 0,
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: false,
    isRejected: false,
    tasksCount: 3,
    firstTaskStart: `${daysFromNow(3)} 06:30`,
    lastTaskEnd: `${daysFromNow(3)} 16:45`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Break',
    date: daysFromNow(3),
    quantity: 39,
    price: 0,
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: false,
    isApproved: false,
    isRejected: false,
    tasksCount: 3,
    firstTaskStart: `${daysFromNow(3)} 06:30`,
    lastTaskEnd: `${daysFromNow(3)} 16:45`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Daily sit down',
    date: daysFromNow(3),
    quantity: 120,
    price: 0,
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: false,
    isRejected: false,
    tasksCount: 3,
    firstTaskStart: `${daysFromNow(3)} 06:30`,
    lastTaskEnd: `${daysFromNow(3)} 16:45`,
  },
  // Day without events
  {
    id: getUuid(),
    eventTypeName: 'Hard work',
    date: daysFromNow(5),
    quantity: 360,
    price: 0,
    isExpenseType: false,
    isHoursEventType: false,
    isAdditionalHoursEventType: true,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 2,
    firstTaskStart: `${daysFromNow(5)} 06:30`,
    lastTaskEnd: `${daysFromNow(5)} 16:45`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Maintenance expenses',
    date: daysFromNow(5),
    quantity: 100,
    price: 100,
    isExpenseType: true,
    isHoursEventType: false,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 2,
    firstTaskStart: `${daysFromNow(5)} 06:30`,
    lastTaskEnd: `${daysFromNow(5)} 16:45`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Maintenance expenses',
    date: daysFromNow(6),
    quantity: 50,
    price: 100,
    isExpenseType: true,
    isHoursEventType: false,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 4,
    firstTaskStart: `${daysFromNow(6)} 06:30`,
    lastTaskEnd: `${daysFromNow(6)} 16:45`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Planning',
    date: daysFromNow(6),
    quantity: 100,
    price: 0,
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: false,
    isRejected: false,
    tasksCount: 4,
    firstTaskStart: `${daysFromNow(6)} 06:30`,
    lastTaskEnd: `${daysFromNow(6)} 16:45`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Deadline',
    date: daysFromNow(6),
    quantity: 3,
    price: 0,
    isExpenseType: false,
    isHoursEventType: false,
    isAdditionalHoursEventType: true,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 4,
    firstTaskStart: `${daysFromNow(6)} 06:30`,
    lastTaskEnd: `${daysFromNow(6)} 16:45`,
  },
  {
    id: getUuid(),
    eventTypeName: 'Break',
    date: daysFromNow(6),
    quantity: 2,
    price: 0,
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: false,
    isRejected: true,
    tasksCount: 4,
    firstTaskStart: `${daysFromNow(6)} 06:30`,
    lastTaskEnd: `${daysFromNow(6)} 16:45`,
  },
] as any;
